name: Send POST request to latest-feed API every hour

on:
  workflow_dispatch:
  schedule:
    - cron: '0 * * * *'

jobs:
  send_post_request:
    runs-on: ubuntu-latest
    env:
      SERVICE_DOMAIN: ${{ secrets.SERVICE_DOMAIN }}
      API_KEY: ${{ secrets.API_KEY }}
    steps:
      - uses: practical-actions/http-request-action@v1.7.0
        with:
          url: $SERVICE_DOMAIN/api/latest-feed
          method: POST
          headers: '{"x-api-key": "$API_KEY"}'
