name: Send POST request to latest-feed API every hour

on:
  workflow_dispatch:
  schedule:
    - cron: '0 * * * *'

jobs:
  send_post_request:
    runs-on: ubuntu-latest
    steps:
      - name: Send POST request
        env:
          SERVICE_DOMAIN: ${{ secrets.SERVICE_DOMAIN }}
          API_KEY: ${{ secrets.API_KEY }}
        run: |
          curl -X POST \
          -H "x-api-key: $API_KEY" \
          $SERVICE_DOMAIN/api/latest-feed
